[project]
name = "albatross"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = ["bird-feeder", "seeds", "flyte"]

[tool.uv.sources]
seeds = { workspace = true }

[tool.uv.workspace]
members = ["packages/seeds"]

[build-system]
requires = ["uv_build>=0.9.3,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
albatross = [
    "numpy",
    "bird-feeder",
]
