[project]
name = "tester"
version = "0.1.0"
description = "Test project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flyte>=2.0.0b22",
    "requests",
    "numpy",
]

[project.optional-dependencies]
pandas = ["pandas", "numpy"]
