[package]
name = "union_rust_controller"
version = "0.1.0"
edition = "2021"

[lib]
name = "union_rust_controller"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
cloudidl = { path = "../../cloud/gen/pb_rust" }
pyo3 = { version = "0.24", features = ["extension-module", "abi3-py310"] }
pyo3-async-runtimes = { version = "0.24", features = ["tokio-runtime"] }
tokio = { version = "1.0", features = ["full"] }
tonic = "0.12"
prost = { version = "0.13.5", features = ["std"] }
prost-types = { version = "0.12", features = ["std"] }
futures = "0.3"
tower = "0.4"
tower-http = { version = "0.5", features = ["trace"] }
tracing = "0.1"
tracing-subscriber = "0.3"
async-trait = "0.1"
thiserror = "1.0"
pyo3-build-config = "0.24.2"

[build-dependencies]
pyo3 = { version = "0.24", features = [
  "extension-module",
  "abi3-py310",
] } # Use your pyo3 version

# Need to do this for some reason otherwise maturin develop fails horribly
# export RUSTFLAGS="-C link-arg=-undefined -C link-arg=dynamic_lookup"
