[build-system]
requires = ["maturin>=1.4,<2.0"]
build-backend = "maturin"

[project]
name = "rust_controller"
version = "0.1.0"
description = "Rust controller for Union"
requires-python = ">=3.10"
classifiers = ["Programming Language :: Python", "Programming Language :: Rust"]

[tool.maturin]
module-name = "flyte_controller_base"
features = ["pyo3/extension-module"]

